const GAMIFICATIONS_ENUM = [
	"COMPLETE_REGISTRATION",
	"COMPLETE_CIRCUIT",
	"COMPLETE_PREMIUM_CIRCUIT",
	"SHARE_WITH_FRIEND",
	"LEAVE_REVIEW",
	"VISIT_POI",
];

module.exports = { GAMIFICATIONS_ENUM };
